name: Lint
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  link:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      - name: Install dependencies
        run: bun install
      - name: Generate code
        run: bun generate
      - name: Run typecheck
        run: bun typecheck
      - name: Run lint
        run: bun lint
